/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SCAN_H_RPCGEN
#define _SCAN_H_RPCGEN

#include <rpc/rpc.h>
#include <rpc/clnt.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Input_file {
	char *fileName;
};
typedef struct Input_file Input_file;

struct Input_dir {
	char *dirName;
	int threshold;
};
typedef struct Input_dir Input_dir;

struct Stat {
	int chars;
	int words;
	int rows;
};
typedef struct Stat Stat;

#define SCANPROG 0x20000013
#define SCANVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define FILE_SCAN 1
extern  Stat * file_scan_1(Input_file *, CLIENT *);
extern  Stat * file_scan_1_svc(Input_file *, struct svc_req *);
#define DIR_SCAN 2
extern  int * dir_scan_1(Input_dir *, CLIENT *);
extern  int * dir_scan_1_svc(Input_dir *, struct svc_req *);
extern int scanprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FILE_SCAN 1
extern  Stat * file_scan_1();
extern  Stat * file_scan_1_svc();
#define DIR_SCAN 2
extern  int * dir_scan_1();
extern  int * dir_scan_1_svc();
extern int scanprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Input_file (XDR *, Input_file*);
extern  bool_t xdr_Input_dir (XDR *, Input_dir*);
extern  bool_t xdr_Stat (XDR *, Stat*);

#else /* K&R C */
extern bool_t xdr_Input_file ();
extern bool_t xdr_Input_dir ();
extern bool_t xdr_Stat ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SCAN_H_RPCGEN */
