/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "scan.h"

Stat *
file_1_svc(Input_file *argp, struct svc_req *rqstp)
{
	static Stat  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
dir_1_svc(Input_dir *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
