/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "scan.h"
#include <sys/stat.h>
#include <sys/types.h>
#include <fcntl.h>
#include <unistd.h>

Stat *
file_1_svc(Input_file *argp, struct svc_req *rqstp)
{
	static Stat  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
dir_1_svc(Input_dir *argp, struct svc_req *rqstp)
{
	static int  result;

    int fd;
    struct stat path_stat;
    result = 0;

	if((dir = opendir(argp->directory)) != NULL){
		while((ent = readdir(dir)) != NULL){
		    if(ent->d_name[0] == '.'){
				if(ent->d_name[1] == '.')
					if(ent->d_name[2] == '\0'){
						continue;
            		}
				if(ent->d_name[1] == '\0'){
					continue;
				}
			}

			stat(ent->d_name, &path_stat);
            if(S_ISREG(path_stat.st_mode) == 0) {
                fd = open(ent->d_name, O_RDONLY);
                if(fd != -1) {
                    if(lseek(fd, 0, SEEK_END) > argp->threshold)
                        result++;
                    close(fd);
                }
            }
		}
	    closedir(dir);
        printf("files (dim>%db): %d\n", argp->threshold, result);
	} else {
		perror("diropen");
	}

	return &result;
}
